### ISSUE TITLE
Android compilation error 5.4.1

### ISSUE THREAD

**Issue by hg-trv** [AppsFlyerSDK/appsflyer-cocos2dx-plugin#10]
# Report

## Plugin Version

5.4.1

## On what Platform are you having the issue?

android

## What did you do?

trying to compile sdk

## What did you expect to happen?

compiled lib

## What happened instead?

compilation error

## Please provide any other relevant information.

`FAILED: libs/appsflyer/CMakeFiles/appsflyer.dir/src/AppsFlyerProxyX.cpp.o
  E:\dev\android\ndk\android-ndk-r21\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --gcc-toolchain=E:/dev/android/ndk/android-ndk-r21/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=E:/dev/android/ndk/android-ndk-r21/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DANDROID -DLWS_WITH_LIBUV -DUSE_FILE32API -I../../../../../../libs/appsflyer/src -I../../../../../../cocos2d -I../../../../../../cocos2d/cocos -I../../../../../../cocos2d/extensions -I../../../../../../cocos2d/cocos/platform -I../../../../../../cocos2d/cocos/base -I../../../../../../cocos2d/cocos/editor-support -I../../../../../../cocos2d/cocos/audio/include -I../../../../../../cocos2d/cocos/platform/android -I../../../../../../cocos2d/external/recast/.. -I../../../../../../cocos2d/external/tinyxml2/. -I../../../../../../cocos2d/external/xxhash/. -I../../../../../../cocos2d/external/xxtea/. -I../../../../../../cocos2d/external/clipper/. -I../../../../../../cocos2d/external/edtaa3func/. -I../../../../../../cocos2d/external/ConvertUTF/. -I../../../../../../cocos2d/external/poly2tri/.. -I../../../../../../cocos2d/external/md5/.. -IE:/dev/android/ndk/android-ndk-r21/sources/android/cpufeatures -I../../../../../../cocos2d/external/android-specific/pvmp3dec/include -I../../../../../../cocos2d/external/android-specific/pvmp3dec/src -I../../../../../../cocos2d/external/android-specific/tremolo/. -I../../../../../../cocos2d/external/unzip/. -isystem ../../../../../../cocos2d/external/Box2D/include -isystem ../../../../../../cocos2d/external/chipmunk/include -isystem ../../../../../../cocos2d/external/freetype2/include/android/freetype2 -isystem ../../../../../../cocos2d/external/jpeg/include/android -isystem ../../../../../../cocos2d/external/uv/include -isystem ../../../../../../cocos2d/external/webp/include/android -isystem ../../../../../../cocos2d/external/bullet/include -isystem ../../../../../../cocos2d/external/bullet/include/bullet -isystem ../../../../../../cocos2d/external/openssl/include/android -isystem ../../../../../../cocos2d/external/tiff/include/android -isystem ../../../../../../cocos2d/external/websockets/include/android -isystem ../../../../../../cocos2d/external/curl/include/android -isystem ../../../../../../cocos2d/external/png/include/android -isystem ../../../../../../cocos2d/external/zlib/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -frtti -fexceptions -fsigned-char -D_DEVELOPER_MODE -O2 -DNDEBUG  -fPIC -std=gnu++11 -MD -MT libs/appsflyer/CMakeFiles/appsflyer.dir/src/AppsFlyerProxyX.cpp.o -MF libs\appsflyer\CMakeFiles\appsflyer.dir\src\AppsFlyerProxyX.cpp.o.d -o libs/appsflyer/CMakeFiles/appsflyer.dir/src/AppsFlyerProxyX.cpp.o -c ../../../../../../libs/appsflyer/src/AppsFlyerProxyX.cpp
  ../../../../../../libs/appsflyer/src/AppsFlyerProxyX.cpp:124:44: error: use of overloaded operator '=' is ambiguous (with operand types 'std::__ndk1::unordered_map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, cocos2d::Value, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<const std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, cocos2d::Value> > >::mapped_type' (aka 'cocos2d::Value') and 'long')
              map[std::string(c_string_key)] = NULL;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~
  ../../../../../../cocos2d/cocos/base/CCValue.h:117:12: note: candidate function
      Value& operator= (unsigned char v);
             ^
  ../../../../../../cocos2d/cocos/base/CCValue.h:119:12: note: candidate function
      Value& operator= (int v);
             ^
  ../../../../../../cocos2d/cocos/base/CCValue.h:121:12: note: candidate function
      Value& operator= (unsigned int v);
             ^
  ../../../../../../cocos2d/cocos/base/CCValue.h:123:12: note: candidate function
      Value& operator= (float v);
             ^
  ../../../../../../cocos2d/cocos/base/CCValue.h:125:12: note: candidate function
      Value& operator= (double v);
             ^
  ../../../../../../cocos2d/cocos/base/CCValue.h:127:12: note: candidate function
      Value& operator= (bool v);
             ^
  ../../../../../../cocos2d/cocos/base/CCValue.h:129:12: note: candidate function
      Value& operator= (const char* v);
             ^
  ../../../../../../cocos2d/cocos/base/CCValue.h:131:12: note: candidate function
      Value& operator= (const std::string& v);
             ^
  1 error generated`

ndk r21
cocos2dx 3.17.2

**Comment by hg-trv** [comment]
can it be replaced with
`map[std::string(c_string_key)] = cocos2d::Value::Null;`
?

**Comment by af-fess** [comment]
hey @hg-trv , thank you, we are checking

**Comment by af-margot** [comment]
Hi @hg-trv , we changed it to` cocos2d::Value::Null ` in the new release 5.4.2. We were not able to reproduce the issue, so please tell us it this fix it for you.

**Comment by hg-trv** [comment]
It compiles now) thank you
